# Generated by Django 3.2.7 on 2026-08-31 03:19

import credit_digitalization.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_number', models.CharField(blank=True, max_length=30, unique=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Diajukan'), ('APPROVED', 'Disetujui'), ('REJECTED', 'Ditolak')], db_index=True, default='DRAFT', max_length=12)),
                ('dealer_name', models.CharField(blank=True, max_length=150, verbose_name='nama dealer')),
                ('dealer_sales_name', models.CharField(blank=True, max_length=150, verbose_name='nama sales dealer')),
                ('consumer_name', models.CharField(blank=True, max_length=150, verbose_name='nama konsumen')),
                ('nik', models.CharField(blank=True, max_length=16, verbose_name='NIK')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='nomor telepon')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='tanggal lahir')),
                ('marital_status', models.CharField(blank=True, choices=[('SINGLE', 'Belum Menikah'), ('MARRIED', 'Menikah'), ('DIVORCED', 'Cerai')], max_length=10, verbose_name='status perkawinan')),
                ('spouse_name', models.CharField(blank=True, max_length=150, verbose_name='nama pasangan')),
                ('consent_personal_data', models.BooleanField(default=False, verbose_name='persetujuan pemrosesan data pribadi')),
                ('vehicle_brand', models.CharField(blank=True, max_length=100, verbose_name='merk kendaraan')),
                ('vehicle_model', models.CharField(blank=True, max_length=100, verbose_name='model kendaraan')),
                ('vehicle_type', models.CharField(blank=True, max_length=100, verbose_name='tipe kendaraan')),
                ('vehicle_color', models.CharField(blank=True, max_length=50, verbose_name='warna kendaraan')),
                ('vehicle_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='harga kendaraan')),
                ('insurance_type', models.CharField(blank=True, choices=[('ALL_RISK', 'All Risk'), ('TLO', 'Total Loss Only (TLO)'), ('COMBINATION', 'Kombinasi')], max_length=15, verbose_name='jenis asuransi')),
                ('down_payment', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='down payment')),
                ('tenor_months', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='lama kredit (bulan)')),
                ('monthly_installment', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='angsuran per bulan')),
                ('ktp_document', models.FileField(blank=True, upload_to=credit_digitalization.models.application_document_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])], verbose_name='KTP')),
                ('family_card_document', models.FileField(blank=True, upload_to=credit_digitalization.models.application_document_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])], verbose_name='kartu keluarga')),
                ('booking_fee_document', models.FileField(blank=True, upload_to=credit_digitalization.models.application_document_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])], verbose_name='bukti bayar tanda jadi')),
                ('application_form_document', models.FileField(blank=True, upload_to=credit_digitalization.models.application_document_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])], verbose_name='form aplikasi pengajuan')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='alasan penolakan')),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_credit_applications', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_credit_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'pengajuan kredit',
                'verbose_name_plural': 'pengajuan kredit',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationAuditTrail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATED', 'Dibuat'), ('UPDATED', 'Diperbarui'), ('SUBMITTED', 'Diajukan'), ('APPROVED', 'Disetujui'), ('REJECTED', 'Ditolak')], max_length=12)),
                ('from_status', models.CharField(blank=True, max_length=12)),
                ('to_status', models.CharField(max_length=12)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_application_activities', to=settings.AUTH_USER_MODEL)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_trails', to='credit_digitalization.creditapplication')),
            ],
            options={
                'verbose_name': 'audit pengajuan',
                'verbose_name_plural': 'audit pengajuan',
                'ordering': ['-created_at'],
            },
        ),
    ]
