# Generated by Django 3.2.7 on 2026-08-31 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_digitalization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditapplication',
            name='consent_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='waktu persetujuan data pribadi'),
        ),
    ]
